steps:
  # Step 1: Deploy langsung ke App Engine tanpa membangun Docker image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.yaml
      - '--quiet'
    dir: '.'  # Menunjuk ke folder frontend saat ini icikiwir

options:
  logging: CLOUD_LOGGING_ONLY  # Opsional: hanya mencatat log ke Google Cloud Logging
