steps:
  # Step 1: Build Docker image dari backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/akbar-backend', '.']

  # Step 2: Push Docker image ke Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/akbar-backend']

  # Step 3: Deploy ke Cloud Run dengan setting env untuk DB
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'akbar-backend',
        '--image', 'gcr.io/$PROJECT_ID/akbar-backend',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--set-env-vars', 'DB_USER=root,DB_PASSWORD=akbar,DB_NAME=tugascc_notes,DB_HOST=34.136.132.0'
      ]
